### ISSUE TITLE
Resizing the window

### ISSUE THREAD

**Issue by skyne98** [jice-nospam/doryen-rs#1] opened 2018-11-15 18:51 UTC
Hey there! Amazing work! I should say, that this might be the best terminal (game-related) renderer I have seen out there! However, even though you have an option to make window resizable, you don't allow hooking up "on resized" events to the window, allowing a user to adapt the rendering to a new window size.

I think it would be a great choice to provide a Window interface, that allows you to get_width() / get_height() as well as set_width() / set_height() for the Console interface. I know it might involve doing a bunch of work, updating the textures and cleaning the buffers, but it is worth it.

Can this be a feature, or do you need help?

**Comment by jice-nospam** [comment] 2018-11-15 18:58
Hey thanks. Definitely something that would be nice to have. I'm currently busy with another project so I won't have much time to spend on this but if you feel like contributing, we can discuss the API changes here and you can submit a merge request.

**Comment by skyne98** [comment] 2018-11-15 19:11
@jice-nospam, I would like to help as soon as I have a little bit of time. Also, at least for me (on linux) there is a bug of graphics rendering in 3/4 of the window, offsetting everything, as well as the cursor.

**Comment by jice-nospam** [comment] 2018-11-16 10:08
I'm using an ubuntu 18.10 and have no issue. Can you show me a screenshot ? The bug appears only when resizing the window ?

**Comment by skyne98** [comment] 2018-11-16 10:50
I am using Ubuntu 18.10 too, so strange, I will send a screen as soon as I am at my computer. Also, resizing fixes the issue, not causes it.

**Comment by jice-nospam** [comment] 2019-02-15 17:16
Closing this since no update. Feel free to reopen if you reproduce

**Closed by jice-nospam** 2019-02-15 17:16 UTC
